[project]
name = "catch-a-waveform-review"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bokeh==2.3.0",
    "librosa==0.8.1",
    "matplotlib>=3.10.8",
    "setuptools>=82.0.0",
    "soundfile==0.10.2",
    "torch==2.0.0",
]
